spring:
  datasource:
    url: jdbc:h2:mem:local;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: create
  security:
    password:


nanoId:
  size : 10

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace
        transaction: trace

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  access-token-expire-time: 10800000 # 3H