spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
  security:
    password:
      iterations: 100000
      hashwidth: 192