spring:
  datasource:
    url: jdbc:h2:mem:local;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      encoding: utf-8
  jpa:
    properties:
        hbm2ddl:
          auto: create
  security:
    password:
      iterations: 100000
      hashwidth: 192
nanoId:
  size : 10


server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  access-token-expire-time: 10800000 # 3H