spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?serverTimezone=UTC&character_set_server=utf8mb4;
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    password:
      iterations: 100000
      hashwidth: 192
nanoId:
  size : 10



server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  access-token-expire-time: 10800000 # 3H