name: Gradle Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Rename JAR
      run: |
        mv $(find build/libs -name "*.jar" ! -name "*-plain.jar") build/libs/app.jar

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: build/libs/app.jar
        
    - name: Upload test reports
      if: always()  
      uses: actions/upload-artifact@v2
      with:
        name: Gradle Test Reports
        path: build/reports/tests/test/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v2
      with:
        name: packaged-jar
        path: ./artifacts
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./artifacts/app.jar" 
        target: "/home/ubuntu/jpashop"
    - name: Move jar File in Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mv /home/ubuntu/jpashop/artifacts/app.jar /home/ubuntu/jpashop/builds/app.jar
          rm -rf /home/ubuntu/jpashop/artifacts


    - name: Restart Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/jpashop
          sudo docker restart jpashop




